
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ruhulamin/result.byteend.com
    - /bin/cp -r * $DEPLOYPATH #copy all from root
    # - /bin/cp -r ./public/* $DEPLOYPATH/
    # - /bin/cp ln -nfs $DEPLOYPATH/public $DEPLOYPATH
    # 1lt2Y9k34kU&X!14
